import type { Metadata } from 'next';
import '../styles/globals.css';
import '../styles/tailwind.css';
import Provider from '@/provider';
import PageLayout from '@/components/layout/PageLayout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Provider>
          <PageLayout>{children}</PageLayout>
        </Provider>
      </body>
    </html>
  );
}
